# Introduction to Numpy

- Numpy is an open source Python library that's used in almost every field of science and engineering. It is universal standard for working with numerical data in Python.

### What is an array?

- An array is a data structure of NumPy library. The elements are all the same type, referred to as array dtype. 

- Anytime you need to use a package or a library you need to make it accessible by importing it. 

In [6]:
import numpy as np
# np is standard annotation, we can use anything instead of np but while caaling it we must use the same word used after as.

# Different methods of creating an array

### Method 1: Using array function

In [7]:
# To create a NumPy array, you can use the function np.array(). We initialize the array inside square brackets []

int_array = np.array([1,2,3,4])
print(int_array)

str_array = np.array(['a','bc','d'])
print(str_array)

[1 2 3 4]
['a' 'bc' 'd']


### Method 2: Using zeroes and ones function

In [9]:
# Creating arrays using only zeroes and ones
zero_array = np.zeros(4)
print(zero_array)

ones_array = np.ones(4)
print(ones_array)

[0. 0. 0. 0.]
[1. 1. 1. 1.]


### Method 3: Using arange  

In [12]:
# Creating an array with a range of evenly spaced intervals
# np.arange(start, stop, step size)

exm_1 = np.arange(1,10,3) # 1 + 3 = 4, 4 + 3 = 7
print(exm_1)

exm_2 = np.arange(2,20,4)
print(exm_2)

[1 4 7]
[ 2  6 10 14 18]


### Method 4: Using linspace 

In [17]:
# We can also use np.linespace() to create an array with values that are spaced linearly in a specified interval
# np.linespace(start, end, total numbers) 

ex_3 = np.linspace(1,10,3) 
print(ex_3)

ex_4 = np.linspace(1,10,5) 
print(ex_4)

# 1 and 10 are the first and last numbers based on total numbers it averages 
# it needs one more number as total numbers is 3, so the average of 1 and 10 is 5.5.

[ 1.   5.5 10. ]
[ 1.    3.25  5.5   7.75 10.  ]


# Sorting, Adding and Removing elements 

### 1. Sorting 

In [21]:
# Sorting
a1 = np.array([2,1,5,3,6,4])
print(np.sort(a1))

a2 = np.array([-1,1,0,-3,-2,3,2])
print(np.sort(a2))

a3 = np.array(['c','b','d','a'])
print(np.sort(a3))

[1 2 3 4 5 6]
[-3 -2 -1  0  1  2  3]
['a' 'b' 'c' 'd']


### 2. Adding/Concatenating 

In [31]:
# Concatenate np.concatenate()
# a is leading array, b is trailing array
a = np.array([1,2,3,4])
b = np.array([5,6])
c = np.array([7,8,9])
print(np.concatenate((a,b,c))) # Careful with the brackets

[1 2 3 4 5 6 7 8 9]


### 3. Deletion 

In [32]:
# Delete elements from an array
# np.delete(array, index)
np.delete(a,3)

array([1, 2, 3])

# Multi-Dimensional Arrays 

In [36]:
# Single dimensional array 
s_dim = np.array([1,2,3,4])
# To get the no of elements in an array
print(s_dim.ndim)
# To get the total elements in an array
print(s_dim.size)
# To get the number of rows and columns
print(s_dim.shape)

1
4
(4,)


In [37]:
# Multi-Dimensional Array with 2 rows and 4 columns
m_dim = np.array([[1,2,3,4],
                [5,6,7,8]])
# To get the no of elements in an array
print(m_dim.ndim)
# To get the total elements in an array
print(m_dim.size)
# To get the number of rows and columns
print(m_dim.shape)

2
8
(2, 4)


In [45]:
# Multi-Dimensional Array with rows, columns and height
mu_dim = np.array([
        [[1,2,3,4],
         [5,6,7,8]],
        [[9,10,11,12],
        [13,14,15,16]]
        ])
# There are 3 square brackets from the outer side when we enter the first one we get the height
# When we move to the second bracket we get the rows
# When we move more columns
# Hence this array contains height of 2, 2 rows and 4 columns

In [44]:
# To get the no of elements in an array
print(mu_dim.ndim)
# To get the total elements in an array
print(m_dim.size)
# To get the number of rows and columns
print(mu_dim.shape)

3
8
(2, 2, 4)


# Indexing and Slicing 

In [47]:
# In Python index always starts from zero, be careful while accessing an element using index
a = np.array([1,2,3,4])

# Accessing last element
print(a[3]) # as there are 4 elements

# Accessing first 2 elements
print(a[0:2]) # Here the element in index 2 won't be included
print(a[:2]) # We don't need to mention zero because the compiler starts from there by default

# Accessing the last 3 elements
print(a[-3:]) # This starts from the last and prints three elements from the last

4
[1 2]
[1 2]
[2 3 4]


In [56]:
# Doing the same in 2 dimensional array
a2 = np.array([[1,2,3],
              [4,5,6]])
# Picking 2 rows and 2nd column
print(a2[:,1]) # Colon for both the rows and index 1 for second column
print(a2[:,:1]) # 2nd column will be excluded as mentioned before 

[2 5]
[[1]
 [4]]


In [51]:
# Subset of an array 
b = np.array([1,2,2,3,4])

# Less than or equal to 3 
print(b[b<=3])

# Divisible by 2
print(b[b % 2 == 0])

# Select elements that are between 2 and 4 
print(b[(b>2)&(b<4)])

# Select elements that are equal to 2 or 4
print(b[(b==2)|(b==4)])

[1 2 2 3]
[2 2 4]
[3]
[2 2 4]


In [55]:
# Logical operators AND (&) and OR (|) have the ability to give out boolean values that can be used to verify a certain condition
c = np.array([1,2,3,4,5,6])

c4 = (c > 4) | (c == 4)
print(c4) # Returns boolean values

print(c[c4]) # Prints the values that came out true to the condition.

[False False False  True  True  True]
[4 5 6]


# Basic Array Operations 

In [57]:
a3 = np.array([2,4,6])
a4 = np.array([1,2,3]) 

In [59]:
# Addition
print(a3+a4) # Should always contain same rows and columns

[3 6 9]


In [60]:
# Subtraction
print(a3-a4)

[1 2 3]


In [61]:
# Division
print(a3/a4)

[2. 2. 2.]


In [62]:
# Multiplication
print(a3*a4)

[ 2  8 18]


In [64]:
# Sum of elements in an array 
a5 = np.array([1,2,3,4])

print(a5.sum())

# Multi-Dimensional
a6 = np.array([[1,1],
             [2,2]])

# Sum across columns
print(a6.sum(axis=0))

# Sum across rows
print(a6.sum(axis=1))

10
[3 3]
[2 4]


### Min, Max, Mean and Standard Deviation 

In [65]:
a7 = np.array([1,2,3,4,5,6,7])

# Minimum of an array
print(a7.min())

# Maximum of an array
print(a7.max())

# Mean of an array
print(a7.mean())

# Standard Deviation of an array
print(a7.std())

1
7
4.0
2.0


In [78]:
# Doing the same on multi-dimensional array
a8 = np.array([[2,1],
              [3,4]])

# Sum
print(a8.sum())

# Maximum
print(a8.max())

# Minimum across column
print(a8.min(axis=0))

# Minimum across row
print(a8.min(axis = 1))

10
4
[2 1]
[1 3]
